### ISSUE TITLE
Creating data_extraction code 

### ISSUE THREAD

**Issue by JulianPetersIsCoding** [course-dprep/team-project-no-vs-code-dprep_fall_2024_group_1#3]
This issue focusses on building the code to extract the needed data from: https://datasets.imdbws.com/.

As mentioned in our team meeting in week 2 we chose to work with the datasets from imdbws.com. In addition, we concluded that we needed data about the ratings, episodes and genres. Meaning that we need to download the following files: "title.ratings.tsv.gz", "title.basics.tsv.gz" and "title.episode.tsv.gz". 

To automate this proces code was written for the assignment in week 2. Meaning that the code needs to be placed at the right location in the new structure. In the assignment the code needed is placed on line 36 to 64, so these lines need to be copied to "Data_Extraction". Do not forget to check if it still runs as intended.  

Kind regards,
Julian Peters

**Comment by jibbebeer** [comment]
Added the code :)

**Comment by JulianPetersIsCoding** [comment]
The code isn't showing. Check the location you pushed it to. 

Kind regards,
Julian Peters
