### ISSUE TITLE
Initialise Project Readme

### ISSUE THREAD

**Issue by srosh2000** [course-dprep/team-project-no-vs-code-dprep_fall_2024_group_1#4]
Welcome to your first GitHub issue!

In this project, we emphasize structured work through the use of GitHub issues to manage tasks. This approach ensures that all contributions are aligned with the project's objectives and allows for efficient collaboration among team members.

Deliverable: Create a README.md file and update it with your research question

Your first task is to create a README.md file in the repository. The README file is essential for informing visitors about the purpose of the repository, its contents, and how they can contribute or use it. For inspiration, consider looking at other repositories within our GitHub organization, such as the [MovieGenre_IMDbAnalysis](https://github.com/course-dprep/MovieGenre_IMDbAnalysis) project.

Getting Started:

Create a Development Branch: Use the sidebar on the right to create a new branch for development purposes.
Switch to Your Development Branch: Update your repository's state to reflect the new branch.
Develop the README.md File: Focus your work on this issue by creating the README.md file directly on GitHub.
Submit a Pull Request: Once your README is ready, submit a pull request to merge your changes.
Merge the Pull Request: Complete the task by merging the pull request into the main branch.
Next Steps:

After completing this task, please move on to your next issue to continue contributing to the project.

Good luck, and thank you for contributing!

**Comment by JulianPetersIsCoding** [comment]
Fleur completed this task.
